# Generated by Django 2.2.6 on 2019-10-06 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostila',
            name='pdf',
            field=models.FileField(blank=True, upload_to='router_specifications'),
        ),
    ]
