# Generated by Django 2.2.6 on 2019-10-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_apostila_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='apostila',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='apostila',
            name='numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número'),
        ),
    ]
