# Generated by Django 2.2.6 on 2019-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20191006_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apostila',
            name='imagem',
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='curso',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
